spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev
 application:
  name: microservicecloud-config-gjc-dev
---
spring:
 profiles: test
 application:
  name: microservicecloud-config-gjc-test
#保存为UTF-8